# Generated by Django 3.2 on 2021-06-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipid', models.IntegerField()),
                ('shname', models.CharField(blank=True, max_length=100, null=True)),
                ('shorig', models.CharField(blank=True, max_length=100, null=True)),
                ('shdest', models.CharField(blank=True, max_length=100, null=True)),
                ('shday', models.CharField(blank=True, max_length=100, null=True)),
                ('con_e', models.IntegerField()),
                ('con_f', models.IntegerField()),
                ('con_s', models.IntegerField()),
            ],
        ),
    ]
